# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - nlandais-test(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Build the container
      run: docker build . -t docker-sample:${{ github.sha }}

#     - name: dotnet publish
#       run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

#     - name: Run Azure webapp deploy action using publish profile credentials
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: nlandais-test
#         slot-name: Production
#         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2C9E93676A054387BFB66D5B45E92A61 }}
#         package: ${{env.DOTNET_ROOT}}/myapp

